#!/usr/bin/env bash
# Update the package list and install HAProxy
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server server1 35.153.57.5:80 check
    server server2 52.87.152.234:80 check
EOL

sudo systemctl enable haproxy
sudo systemctl restart haproxy
